### ISSUE TITLE
Grunt Install

### ISSUE THREAD

**Issue by mappum** [ipfs/node-ipfs#12]
The project currently uses Make to automate installation. This hurts portability, since Windows developers would need Cygwin or something similar. Grunt is a much better alternative since Node developers are used to it and it is fully cross-platform (since it's Node-based).

Resolving #11 would eliminate the need for a build system since the project could be installed via NPM.

**Comment by diasdavid** [comment]
Closing this issue as it referes to the 1st impl of node-ipfs that is no longer supported (as we are building the new one compliant with the spec :) ).
