### ISSUE TITLE
Guide for review

### ISSUE THREAD

**Issue by diasdavid** [ipfs/node-ipfs#15]
@RichardLitt, thank you so much for helping me review stuff, as I explain in IRC, there isn't exactly PR to review, since I'm pretty much the only one maintaining the code and I just keep iterating over master till we hit a alpha version.

There is a simple ['roadmap' in this repo's Readme](https://github.com/ipfs/node-ipfs/blob/master/README.md#roadmap), however, if it is the first time you are dialing in to libp2p, it might not be clear what is going on. For that, I've a WIP of the libp2p spec, it does explain a lot, unfortunately not all, yet. You can find it here - https://github.com/ipfs/specs/pull/19 

In terms of reviewing code, the best place to start would be by the Swarm components, which handles dialing, protocol muxing, stream muxing and Identify. It is what every other component uses so that they can open streams between peers.

**Comment by RichardLitt** [comment]
@diasdavid Thanks for writing this up! Good to know there's no real PRs to review, just general overall QAQC. Will see what I can do. I don't understand pretty much anything of what is said in ipfs/specs#19, but I'm thinking of starting a document for technical overview and discussion to help out a) me b) future people like me. 

I'll add reviewing swarm components to my log of things to do. Sounds good. Thanks.
