### ISSUE TITLE
DHT implementation

### ISSUE THREAD

**Issue by jbenet** [ipfs/node-ipfs#3]
The next major subsystem to do is the DHT.

The rough plan in order of importance:
- [ ] basic kademlia alg (ipfs-dht) <-- enough for now.
- [ ] coral locality clusters (ipfs-dht)
- [ ] s/kademlia disjoint path lookups (ipfs-dht)
- [ ] s/kademlia peer addressing (ipfs-peer)
- [ ] s/kademlia signatures (ipfs-msgproto-crypto)

Note that this module should work on top of a [msgproto](https://github.com/jbenet/node-ipfs-msgproto) packet stream. msgproto handles all standard encapsulation (network, integrity, signing, etc).

**Comment by martindale** [comment]
There is now also [gordonwritescode/kad](http://github.com/gordonwritescode/kad).  Solid.

**Comment by jbenet** [comment]
@martindale thanks!

**Comment by diasdavid** [comment]
@jbenet if you happen to have something on the DHT spec written down already, please feel free to push it so I can start on it tomorrow fresh and early :)

**Comment by diasdavid** [comment]
Closing this issue as it referes to the 1st impl of node-ipfs that is no longer supported (as we are building the new one compliant with the spec :) ).
